### ISSUE TITLE
[Bug]: Visual incompatibility with Dyed

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Fuzss/betteranimationscollection#10]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.3

### Notes (Required)

Horse armor doesn't follow a horse's movement when equipped, if both [Dyed](https://www.curseforge.com/minecraft/mc-mods/dyed) and BAC are installed together. Even if the armor is not leather.

![2022-10-16_18 12 38](https://user-images.githubusercontent.com/86702831/196046209-c1b3eb4d-0c2d-4437-ba8a-88278511e03e.png)

**Comment by Fuzss** [comment]
Hmm, the way that mod is made would require for dedicated mod compatibility one my side which I'm not very keen on as it's such a small mod.

I'll ask the mod author to adjust their code a little so that BAC will be compatible without any dedicated integration.

**Comment by Footage2-Amply-Pounce** [comment]
Should be fixed: https://github.com/yurisuika/Dyed/releases/tag/1.1.0
