### ISSUE TITLE
[Bug]: floating dog collar

### ISSUE THREAD

**Issue by FroofyFroof** [Fuzss/betteranimationscollection#11]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.0 upwards 

### Notes (Required)

The dogs collar floats if it lays or sits down
![2022-10-17_23 00 21](https://user-images.githubusercontent.com/116037656/196285995-77ecbc95-779a-42fd-9e7a-4775c37885cd.png)

**Comment by Fuzss** [comment]
I can't reproduce the issue, does this version maybe fix it?
https://mega.nz/file/fd1lgaQJ#yp3DkvOKrWWdKdRLoM4-ZF_Bvp423y64KPWjsUpdQGE

If not would be great if you could list all other mods that somehow affect wolves.

**Comment by FroofyFroof** [comment]
I dont have any mods that change things about dog/wolves. i also diabled the shader and resource pack but changed nothing

**Comment by FroofyFroof** [comment]
i even installed in in a new profile with just forge installed and it does the same thing

**Comment by Fuzss** [comment]
The version i posted doesn’t help?

**Comment by Fuzss** [comment]
Do you have the latest version of Forge? Did you change anything in the config?

I also tried around with a completely fresh profile and I'm still unable to reproduce this issue.

**Comment by DakkPasserida** [comment]
I did some testing, as I also experience this, and it appears that Optifine causes it in my case.
The collar was properly attached to the wolf when Optifine's disabled, and it floats when it's enabled.

**Comment by Fuzss** [comment]
Thanks for the input, I can confirm that this only happens with OptiFine installed.

There is no point in me even attempting to provide some compatibility, so the only I can recommend is to disable to animated wolf model in the client config.

**Comment by Fuzss** [comment]
Alternatively you could possible look into the OptiFine alternatives on Forge for shaders and so, not sure what the current mods are called though.

**Comment by Lozf** [comment]
Would it be possible to have an option to disable the collar while laying down?

**Comment by Fuzss** [comment]
No you can only disable the whole model.

**Comment by sigmaminecrafter** [comment]
Happens to me on my 1.20,1 fabric modpack
I have more mob variants mod which adds wolf variants but idk if thats why
The collar isnt anchored on the dog properly its like floating above at all times

**Comment by sigmaminecrafter** [comment]
Oh wait this is slleeping dogs lie mod
This broke my wolf chest model it looked like my wolfs got hit by a plane
