### ISSUE TITLE
[Crash]: Crashes on start when using both this mod and effective mod

### ISSUE THREAD

**Issue by cjkop10** [Fuzss/betteranimationscollection#13]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

1.19.2

### Notes (Required)

Hello, I am having constant crashes on game start up. I have a link to the Crash Report below.  It seems to happen when using the effective mod with this mod (link below).  Also, I was using the Effective-1.4.Jar version created on Oct 21, 2022 for Fabric.  As of this mod, I was using the [FABRIC] [p1.19.2] BetterAnimationsCollection-v4.0.4 version created on Oct 19, 2022 for Fabric.  I was also using about 20 more light mods just to enhance the game slightly.  If u need those lmk.  Hopefully this helps.

https://www.curseforge.com/minecraft/mc-mods/effective/files

### Crash Report (Required)

https://docs.google.com/document/d/1Ab7gW6ZhVB_broCXVCf5KomFDm99EeHSmsCLJBURdD0/edit?usp=sharing

**Comment by Fuzss** [comment]
Thanks for the report. This has nothing to do with BAC though, you are simply missing a library mod for Effective: https://www.curseforge.com/minecraft/mc-mods/satin-api
Unfortunately Effective does not properly define this library as a dependency, therefore the Fabric loader is unable to tell you about it missing and instead directly gives you `java.lang.NoClassDefFoundError`.
