### ISSUE TITLE
[Crash]: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Fuzss** [Fuzss/betteranimationscollection#14]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.4

### Notes (Required)

On config reload

### Crash Report (Required)

https://mclo.gs/nFzIT20

**Comment by ChromaPIE** [comment]
Forge version has the same issue too, but it happens when loading the game and causing a crash on startup.

**Comment by Fuzss** [comment]
Should be fixed as of v4.0.5.
