### ISSUE TITLE
[Suggestion]: Update to 1.19.3

### ISSUE THREAD

**Issue by Marsephel** [Fuzss/betteranimationscollection#17]
### Suggestion (Required)

Current supported fabric version is 1.19.2, however many mods are now on 1.19.3 and I currently cannot use the betteranimations collection with 1.19.3, would be great to see an update to allow using with the current version of other fabric mods.

**Comment by Neuxs0** [comment]
I have been waiting so long for a 1.19.3 update, and nothing...

**Comment by Ghayes12** [comment]
> I have been waiting so long for a 1.19.3 update, and nothing...

yeah, same... I found out about this mod during 1.19.2 but didn't get around to trying it out until I updated my server to 1.19.3. So I still have yet to give it a shot. I imagine they will come out with an update eventually, but it is hard to be patient
