### ISSUE TITLE
[Bug]: wolf collar visual bug

### ISSUE THREAD

**Issue by MrKashew** [Fuzss/betteranimationscollection#19]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

v6.0.0

### Notes (Required)

screenshot of wolf collar visual bug
also have domestication innovation - not sure what other mods can be affecting it I can send modlist if it is not caused by this mod itself
https://gyazo.com/8c2f6b3d387dead37f8a02cca35d83b7

**Comment by Fuzss** [comment]
Thanks for reporting! See #11.
