### ISSUE TITLE
[Bug]: Incompatible with Entity Model Features

### ISSUE THREAD

**Issue by nekochuc** [Fuzss/betteranimationscollection#20]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

6.0.0

### Notes (Required)

Incompatible with Entity Model Features
When using the Better Animations Collection
My 3d texture cannot be loaded

**Comment by Fuzss** [comment]
I need more information about this. What 3d textures cannot be loaded, what resource packs are you using, and also provide your latest.log.

**Comment by nekochuc** [comment]
what is atest.log ?
i use https://mizunomcmemo.blogspot.com/ this
mizuno resource packs 

as it should be look like this - https://cdn.discordapp.com/attachments/895794126417719339/1113516518710460548/image.png

but now - https://cdn.discordapp.com/attachments/1109890675895451830/1109890676335845467/image.png

**Comment by Fuzss** [comment]
disable the villager model in the betteranimationscollection config
