### ISSUE TITLE
[Suggestion]: config file to disable any particular animation

### ISSUE THREAD

**Issue by SLinxTheFox** [Fuzss/betteranimationscollection#21]
### Suggestion (Required)

for example, i don't want creeper wobble or enderman flailies, but the rest are amazing. If you're willing to do it it'd be much appreciated

Also thanks for updating your stuff to 1.19.4, you've made a lot of really nice mods and it was a shame to not be able to use them

**Comment by Fuzss** [comment]
That’s already a thing. You need the Configured mod to access the configs in-game. Or edit the file manually in the config directory.
