### ISSUE TITLE
[Bug]: Animations not loading

### ISSUE THREAD

**Issue by Ialeitan** [Fuzss/betteranimationscollection#23]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

After booting up the game, and loading a world, all mobs I see use standard animations. 
(I suspect a conflict, but I am very new to this. Apologies.)

### latest.log (Optional)

https://gist.github.com/Ialeitan/c555f01703f2e0b78db5383f1eecc361

**Comment by Fuzss** [comment]
Likely a mod conflict. Please try with just BAC (+dependencies) installed.

**Comment by Ialeitan** [comment]
Ok. I installed only this mod (+dependencies) on 2 separate instances. One instance of Simply optimized and one of fabulously optimized. SO worked fine. FO did not work. Would sending the log for FO be helpful?

**Comment by Ialeitan** [comment]
K. Seems like EMF [Entity model features] was the culprit. Disabled it. Thanks! @Fuzss
