### ISSUE TITLE
[Bug]: dog collar floating when sat down

### ISSUE THREAD

**Issue by 0ixti** [Fuzss/betteranimationscollection#27]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

1.20.1 forge

### Notes (Required)

when my tamed dog sits down it's collar is floating above it's head when he's sat/laying down I made [a reddit post showcasing it](https://www.reddit.com/user/i_mii/comments/173f9yz/dog_collar/)

**Comment by Fuzss** [comment]
This is an issue with shaders when using Optifine if I remember correctly, there is nothing I can do about it.
