### ISSUE TITLE
[Suggestion]: Being able to configure like disable all mobs and enable some mobs animation.

### ISSUE THREAD

**Issue by makumaku1974** [Fuzss/betteranimationscollection#29]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.21

### Mod Version(s) (Optional)

21.0.0

### Suggestion (Required)

An on/off feature that would disable or enable what animations i want to be animated.

**Comment by makumaku1974** [comment]
This is all mobs that I'm referring.

**Comment by Fuzss** [comment]
Use the config via Mod Menu for that.
