### ISSUE TITLE
[Bug]: Animations not showing

### ISSUE THREAD

**Issue by Jambo199** [Fuzss/betteranimationscollection#30]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

v21.0.0-1.21-Fabric

### Other Mods Involved (Required)

Yes

### Notes (Required)

I loaded in but none of the animations were actually applied. and yes i checked if the mod was installed.

### latest.log (Required)

https://gist.github.com/Jambo199/72170b5a3baa708f3d994b9005a8f408

**Comment by Fuzss** [comment]
Do the animations still not work when only BAC is installed?

**Comment by Jambo199** [comment]
let me check

**Comment by Jambo199** [comment]
right now, i am slowly disabling the mods which might be conflicting with it

**Comment by Jambo199** [comment]
ok, i found the mod which causes the animations to not work, the mod is called 'ModernFix'
Hope this helps so that you can say what the mod is compatible with
