### ISSUE TITLE
[Suggestion]: Ability to enable/disable animations on a by-creature basis

### ISSUE THREAD

**Issue by Taolan13** [Fuzss/betteranimationscollection#31]
### Mod Loader (Optional)

Forge

### Suggestion (Required)

So, my play group uses a modpack with this mod installed (and the mod options menu thing), but they are quite squeemed out by some of the animations. The wobbly creeper, as an example, has been described by several people as a 'floppy green dildo' and even knowing the inspiration for the animation I can no longer unsee this comparison.

We do appreciate the ability to change certain animation parameters, as we've all used that to customize our experiences, but would it be at all possible to add individual enable/disable for the custom animations on a by-mob basis? We really like most of the animations provided and don't want to remove the mod in its entirety but it would be nice to be able to enable/disable specific creatures, especially in the case of having multiple animation mods where some might conflict.

**Comment by Fuzss** [comment]
Check the models section of the config for a toggle for each individual model.

Also in case you were wondering that is the inspiration for the Creeper: https://youtu.be/k2rDbRUDkds?si=i9ALCVAXyJzIUHtk&t=82
