### ISSUE TITLE
Incompatibility with WolfArmor

### ISSUE THREAD

**Issue by jacraff** [Fuzss/betteranimationscollection#4]
I cannot have these two mods installed simultaneously unless I turn off the Wolf Feature off in config. The issue stems from not being able to render the fluffy tail but when I disable that specific feature in config, the game still crashes for the same reason.

[crash-2020-01-08_14.12.44-client.txt](https://github.com/Fuzss/betteranimationscollection2/files/4033471/crash-2020-01-08_14.12.44-client.txt)

I've also submitted this on the WolfArmor issue tracker.

**Comment by Fuzss** [comment]
Completely disabling wolf animations is the only solution. 

It's no very hard to make both mods compatible, but I don't have the time to implement this feature in the foreseeable future.

**Comment by Fuzss** [comment]
1.12 is now unsupported unfortunately.
