### ISSUE TITLE
Incompat with mods whose renders call null

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/betteranimationscollection#6]
`Forge v36.2.4`
 `Minecraft v1.16.5`
 `Better Animations Collection v1.2b6`
 [`Whisperwoods v2.0.2`](https://www.curseforge.com/minecraft/mc-mods/whisperwoods)

- If Whisperwoods or Pokecube pre v0.13.0.b is installed, an error is printed out to the logs, and animated mobs are not animated. Pokecube has patched this by removing the null called in `RenderPokemob`, but I've also discovered that Whisperwoods has the same problem.
- I've reported this to Whisperwoods at itsmeow/whisperwoods#33
- This is at least one spot where they use a null: https://github.com/itsmeow/whisperwoods/blob/12a05528149c9b3ff7eb101beb95738d0ae6a37f/src/main/java/dev/itsmeow/whisperwoods/client/renderer/entity/RenderWisp.java#L27
- This is where Pokecube had a similar incompat, which was able to be fixed by replacing the null in the render: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/commit/94a3292d7d358eff89f94c175976a0e7cec67ff7
 - [Error Log](https://gist.github.com/WenXin20/2894c95427eae15346decfb566022ca7#file-whisperwoods_betteranimationscollection_error-log-L1483)

**Comment by Fuzss** [comment]
Fixed in v1.2.4.
