### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Flame1211** [Fuzss/betteranimationscollection#7]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.0

### Notes (Required)

game launches, and when it gets to the main menu I'm hit with a crash notification from not enough crashes, issue stops when the mod is removed.

### Crash Report (Required)

https://crashy.net/5FcvLNkWoTBD1KfRdyUe

### latest.log (Optional)

https://pastebin.com/eVnH1uzh

**Comment by Fuzss** [comment]
Does v4.0.1 fix your issue?

**Comment by Flame1211** [comment]
yes'ir everything seems fine now!

**Comment by Fuzss** [comment]
Awesome!
