### ISSUE TITLE
[Crash]: big crash

### ISSUE THREAD

**Issue by wuggyfoot** [Fuzss/betteranimationscollection#8]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.0

### Notes (Required)

launch game, after some loading big crash appears. disabled rubidium, starlight, etc.... still crash

### Crash Report (Required)

https://crashy.net/hARBeLe0WnN1Pd5GC9gj

### latest.log (Optional)

https://pastebin.com/cSJbLQDi

**Comment by Fuzss** [comment]
Does v4.0.1 fix your issue?

**Comment by wuggyfoot** [comment]
It does work.

**Comment by wuggyfoot** [comment]
Epic mod BTW x3

**Comment by Fuzss** [comment]
Awesome, and thanks! :)
