### ISSUE TITLE
[Bug]: Defect armored hostile mob

### ISSUE THREAD

**Issue by Psychodeus** [Fuzss/betteranimationscollection#9]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.2

### Notes (Required)

![2022-10-15_22 43 33](https://user-images.githubusercontent.com/93028949/196001963-29843b7d-6413-4af0-a8ea-95e37a17e438.png)
![2022-10-15_23 12 34](https://user-images.githubusercontent.com/93028949/196001970-8c71db67-557a-49a5-add9-ff0835eebdfc.png)

It was fine before installing this mod. with or without shaders.

### latest.log (Optional)

https://gist.github.com/Psychodeus/ed1080ce264e93646992aa33965a4d55

**Comment by Fuzss** [comment]
Thanks, fixed in v4.0.3.

Btw what mod is the neat health bar from?

**Comment by Psychodeus** [comment]
@Fuzss It was from [Torohealth](https://www.curseforge.com/minecraft/mc-mods/torohealth-damage-indicators), but it need to set in config file since they don't have config in ModMenu. Here is the config if you want to be like the screenshoot:

{
  "watchForChanges": true,
  "hud": {
    "distance": 60,
    "x": 4.0,
    "y": 4.0,
    "scale": 1.0,
    "hideDelay": 20,
    "anchorPoint": "TOP_LEFT",
    "showEntity": true,
    "showBar": true,
    "showSkin": true,
    "onlyWhenHurt": false
  },
  "bar": {
    "damageNumberType": "LAST",
    "friendColor": "#00ff00",
    "friendColorSecondary": "#008000",
    "foeColor": "#ff0000",
    "foeColorSecondary": "#800000"
  },
  "inWorld": {
    "mode": "WHEN_HOLDING_WEAPON",
    "distance": 60.0,
    "onlyWhenLookingAt": true,
    "onlyWhenHurt": false
  },
  "particle": {
    "show": true,
    "damageColor": "#ff0000",
    "healColor": "#00ff00",
    "distance": 60
  }
}

**Comment by Fuzss** [comment]
That's really cool, thanks a lot!

**Comment by Psychodeus** [comment]
I thank you too for the v4.0.3 ^^
